llm_sherpa:
  api_url: http://localhost:5010/api/parseDocument?renderFormat=all
openrouter:
  api_key: ''
  site_url: http://localhost:3000
  site_name: HybridRAG
  model: anthropic/claude-3.5-haiku-20241022
llm:
  extraction_model: anthropic/claude-3.5-haiku-20241022:beta
  answer_model: openai/gpt-4o-mini-2024-07-18
graph:
  storage:
    nodes_file: data/graphs/nodes.csv
    edges_file: data/graphs/edges.csv
  node_limit: 150
  min_degree: 2
  text_weight: 0.6
  centrality_weight: 0.4
embedding:
  model_name: thenlper/gte-small
  max_length: 512
  cache_dir: /fastembed_cache
ranking:
  model_name: cross-encoder/ms-marco-MiniLM-L-12-v2
  cache_dir: data/cache/reranker
document:
  supported_formats:
  - pdf
  - docx
  - txt
  chunk_size: 512
  chunk_overlap: 50
cache:
  directory: data/cache
  ttl_hours: 24
  max_size_gb: 10
processing:
  batch_size: 1000
  max_workers: null
  use_process_pool: true
  use_thread_pool: true
logging:
  log_level: INFO
  max_log_size: 5242880
  backup_count: 3
  loggers:
    werkzeug:
      level: WARNING
      propagate: false
    flask:
      level: INFO
      propagate: false
    src.processing_layer.graph_constructor:
      level: WARNING
      propagate: true
    root:
      level: INFO
      handlers:
      - file
      - console
  handlers:
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: detailed
      filename: logs/app.log
      maxBytes: 5242880
      backupCount: 3
    console:
      class: logging.StreamHandler
      formatter: simple
      level: INFO
  formatters:
    detailed:
      format: '%(asctime)s - %(levelname)s - %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
    simple:
      format: '%(levelname)s - %(message)s'
  filters:
    ignore_repeated:
      class: logging.Filter
      name: repeated_filter
timeouts:
  document_processing: 20
  query_processing: 30
  embedding_generation: 60

retrieval:
  initial_pool_size: 250
  score_threshold: 0.75
  rerank_size: 75

diversity:
  enable_penalty: true
  penalty_factor: 0.05
  max_penalty: 0.3
  min_source_types: 3
paths:
  embeddings: data/embeddings
  graphs: data/graphs
  raw_documents: data/raw_documents
  processed_chunks: data/processed_chunks
  models:
    gte_small: models/gte_small
    translation_ar_en: models/opus-mt-ar-en
    translation_en_ar: models/opus-mt-en-ar
    ranking: models/ranking_model
